<!-- 

https://www.reddit.com/r/youtubedl/comments/13izxi0/ytdlp_playlist_to_json/
    
does it have to be json? you start by saying you want video id's.

yt-dlp -s --flat-playlist --print-to-file id,title fileTitle.json "Playlsit URL"
after loading the playlist pages (each page has 30 videos), it's blazingly fast because the --flat-playlist option means it's not checking each video for extra metadata.

-->

<script>
  // the dmt data generated by the script gets pasted into this variable
  let DMT_DATA = [
    {
      id: "jlBn7KjdVFg",
      last_name: "SAMPAIO ROMAO",
      first_name: "Tiago",
      country: "POR",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "2if0wjjp0GA",
      last_name: "TLAKA Sebolai",
      first_name: "Offering",
      country: "RSA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "T5mJPTy0fK8",
      last_name: "TINGELOEF",
      first_name: "Gustav",
      country: "SWE",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "W7fcrmJb1Q4",
      last_name: "ZHANG",
      first_name: "Xiaoxiao",
      country: "CHN",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "aFqOSwuboAs",
      last_name: "THOMAS",
      first_name: "Braida",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "YWDuHoTTmEY",
      last_name: "MAPEKA",
      first_name: "Star",
      country: "RSA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "cAA8hQhvJMM",
      last_name: "PEREZ",
      first_name: "Daniel",
      country: "ESP",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "1kW0Q6hyEKc",
      last_name: "SHEEHAN",
      first_name: "Ryan",
      country: "CAN",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "KaMnz9qaviQ",
      last_name: "MILLER-BURKO",
      first_name: "Jordyn",
      country: "CAN",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "W7fcrmJb1Q4",
      last_name: "ZHANG",
      first_name: "Xiaoxiao",
      country: "CHN",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "YWDuHoTTmEY",
      last_name: "MAPEKA",
      first_name: "Star",
      country: "RSA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "aFqOSwuboAs",
      last_name: "THOMAS",
      first_name: "Braida",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "qXqfnTYstlU",
      last_name: "HAGARTY",
      first_name: "Carina",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "mUJGk2EfgXo",
      last_name: "NEL",
      first_name: "Keara",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "KSuBqVG6RWg",
      last_name: "LOWELL",
      first_name: "Kristle",
      country: "USA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "HQ47Hf2kC9I",
      last_name: "NEL",
      first_name: "Keara",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "nrsa_sA9Mik",
      last_name: "SHEEHAN",
      first_name: "Ryan",
      country: "CAN",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "1kW0Q6hyEKc",
      last_name: "SHEEHAN",
      first_name: "Ryan",
      country: "CAN",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "QmxFIFB5FVs",
      last_name: "GRAY",
      first_name: "Rhys",
      country: "GBR",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "D3UdDQ4Uu7Q",
      last_name: "VALCARCEL",
      first_name: "Juan",
      country: "COL",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "tRUfwsUBpEo",
      last_name: "LOWELL",
      first_name: "Kristle",
      country: "USA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "c5Ajrt3T8V8",
      last_name: "DEVINE",
      first_name: "Ryan",
      country: "GBR",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "cAA8hQhvJMM",
      last_name: "PEREZ",
      first_name: "Daniel",
      country: "ESP",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "sUWXzt8nlOw",
      last_name: "MAPEKA",
      first_name: "Star",
      country: "RSA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "V7-e88jdxhA",
      last_name: "GILBERT",
      first_name: "Owen",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "-pVUghd749c",
      last_name: "KENNEDY",
      first_name: "Alexa",
      country: "NZL",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "3adZyvMun6U",
      last_name: "RHOADES",
      first_name: "Carter",
      country: "USA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "aqdJAO-oAjw",
      last_name: "BEATTIE",
      first_name: "Kim",
      country: "GBR",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "fxTMaRop8lE",
      last_name: "SCHMIDT",
      first_name: "Daniel",
      country: "GER",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "2if0wjjp0GA",
      last_name: "TLAKA Sebolai",
      first_name: "Offering",
      country: "RSA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "jlBn7KjdVFg",
      last_name: "SAMPAIO ROMAO",
      first_name: "Tiago",
      country: "POR",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "8pbmByiMOTU",
      last_name: "PADILLA",
      first_name: "Ruben",
      country: "USA",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "JA-MuxL13_g",
      last_name: "HATFIELD",
      first_name: "Ryan",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "T5mJPTy0fK8",
      last_name: "TINGELOEF",
      first_name: "Gustav",
      country: "SWE",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "NWsQ9kHhLPs",
      last_name: "AQUINO",
      first_name: "Bernardo",
      country: "ARG",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "hUO1JHZUDU8",
      last_name: "O'BRIEN",
      first_name: "Caitlin",
      country: "GBR",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "OWm7Aw5n1EQ",
      last_name: "VALCARCEL",
      first_name: "Juan",
      country: "COL",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "KaMnz9qaviQ",
      last_name: "MILLER-BURKO",
      first_name: "Jordyn",
      country: "CAN",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
    {
      id: "l6wVNvHs1-E",
      last_name: "HATFIELD",
      first_name: "Ryan",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "1FGj-qj3858",
      last_name: "AXELSEN",
      first_name: "Damien",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 2",
    },
    {
      id: "moRxt2bDQXE",
      last_name: "AXELSEN",
      first_name: "Damien",
      country: "AUS",
      gender: null,
      event: "2018 Trampoline Worlds",
      round: "Qualification Exercise 1",
    },
  ];

  let entry = DMT_DATA[0];

  let routinesIncluded = [];

  console.log(DMT_DATA.length);

  const startAt = 10;
</script>

<!-- this comes from the packge svelte-youtube-embed
    I would like the video to autoplay when the page loads
    starting 5 seconds in -->
<iframe
  title="ytvideo"
  src="https://www.youtube.com/embed/{entry.id}?autoplay=1&start={startAt}&rel=0"
  frameborder="0"
  allow="autoplay; picture-in-picture; clipboard-write"
  allowfullscreen
  width="800"
  height="450"
  id="ytplayer"
/>
<input
  type="text"
  on:keydown={(e) => {
    // for some reason intelisense thinks "value" is not an attribute of e.target, but it works
    // on enter, update the input store and clear the input bar
    if (e.key === "Enter") {
      const info = e.target.value.split(" ");
      entry["skills"] = [info[0], info[1]];
      // old score entry here since the scoring system changed in 2022
      // since 2022 and 2023 have been transcribed, we just use the old system
      // old scores get converted to new scores for the sake of sorting by execution
      entry["scoreOld"] = info[2];
      // console.log(entry);
      routinesIncluded.push(entry);
      localStorage.setItem("routines", JSON.stringify(routinesIncluded));
      e.target.value = "";
      DMT_DATA.shift();
      entry = DMT_DATA[0];
      console.log(localStorage.get("routines"));
    } else if ("^f(o</".includes(e.key)) {
      //e.target.value += " ";
    } else if (e.key === "q") {
      console.log(routinesIncluded);
      e.preventDefault();
    } else if (e.key === "]" || e.key === "[") {
      e.target.value = "";
      DMT_DATA.shift();
      entry = DMT_DATA[0];
    }
  }}
/>

<style>
  input {
    width: 100%;
    height: 50px;
    font-size: 40px;
    margin: 20px 0px;
  }

  /* easier on the eyes */
  :global(body) {
    background: black;
    color: white;
  }
</style>
