<!-- 

https://www.reddit.com/r/youtubedl/comments/13izxi0/ytdlp_playlist_to_json/
    
does it have to be json? you start by saying you want video id's.

yt-dlp -s --flat-playlist --print-to-file id,title fileTitle.json "Playlsit URL"
after loading the playlist pages (each page has 30 videos), it's blazingly fast because the --flat-playlist option means it's not checking each video for extra metadata.

-->

<script>
  // the dmt data generated by the script gets pasted into this variable
  let DMT_DATA = [];
  let entry = DMT_DATA[0];

  let routinesIncluded = [];

  console.log(DMT_DATA.length);

  const startAt = 10;
</script>

<!-- this comes from the packge svelte-youtube-embed
    I would like the video to autoplay when the page loads
    starting 5 seconds in -->
<iframe
  title="ytvideo"
  src="https://www.youtube.com/embed/{entry.id}?autoplay=1&start={startAt}&rel=0"
  frameborder="0"
  allow="autoplay; picture-in-picture; clipboard-write"
  allowfullscreen
  width="800"
  height="450"
  id="ytplayer"
/>
<input
  type="text"
  on:keydown={(e) => {
    // for some reason intelisense thinks "value" is not an attribute of e.target, but it works
    // on enter, update the input store and clear the input bar
    if (e.key === "Enter") {
      const info = e.target.value.split(" ");
      entry["skills"] = [info[0], info[1]];
      // old score entry here since the scoring system changed in 2022
      // since 2022 and 2023 have been transcribed, we just use the old system
      // old scores get converted to new scores for the sake of sorting by execution
      entry["scoreOld"] = info[2];
      // console.log(entry);
      routinesIncluded.push(entry);
      localStorage.setItem("routines", JSON.stringify(routinesIncluded));
      e.target.value = "";
      DMT_DATA.shift();
      entry = DMT_DATA[0];
      console.log(localStorage.get("routines"));
    } else if ("^f(o</".includes(e.key)) {
      //e.target.value += " ";
    } else if (e.key === "q") {
      console.log(routinesIncluded);
      e.preventDefault();
    } else if (e.key === "]" || e.key === "[") {
      e.target.value = "";
      DMT_DATA.shift();
      entry = DMT_DATA[0];
    }
  }}
/>

<style>
  input {
    width: 100%;
    height: 50px;
    font-size: 40px;
    margin: 20px 0px;
  }

  /* easier on the eyes */
  :global(body) {
    background: black;
    color: white;
  }
</style>
